# Generated by Django 2.2.7 on 2019-12-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chip_num', models.CharField(blank=True, max_length=20, verbose_name='晶片號碼')),
                ('animal_type', models.IntegerField(choices=[(0, '狗'), (1, '貓'), (2, '其他')], default=0, verbose_name='種類')),
                ('breed', models.CharField(default='', max_length=20, verbose_name='品種')),
                ('age', models.IntegerField(choices=[(0, '幼年'), (1, '成年'), (2, '老年')], default=0, verbose_name='年紀')),
                ('sex', models.CharField(choices=[('male', '公'), ('Female', '母')], default='公', max_length=32, verbose_name='性別')),
                ('location', models.IntegerField(choices=[(0, '台北市'), (1, '新北市'), (2, '桃園市'), (3, '新竹縣'), (4, '新竹市'), (5, '苗栗縣'), (6, '台中市'), (7, '彰化縣'), (8, '南投縣'), (9, '雲林縣'), (10, '嘉義縣'), (11, '嘉義市'), (12, '台南市'), (13, '高雄市'), (14, '屏東縣'), (15, '台東縣'), (16, '花蓮縣'), (17, '宜蘭縣')], default=0, verbose_name='來源地')),
                ('health', models.CharField(default='', max_length=20, verbose_name='健康狀態')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('photo', models.ImageField(null=True, upload_to='pet')),
                ('state', models.IntegerField(choices=[(0, '待認養'), (1, '已領養')], default=0, verbose_name='領養狀態')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=20, verbose_name='名字')),
                ('Sex', models.CharField(blank=True, max_length=20, verbose_name='性別')),
                ('Type', models.CharField(blank=True, max_length=20, verbose_name='種類')),
                ('Build', models.CharField(default='', max_length=20, verbose_name='體型')),
                ('Age', models.CharField(blank=True, max_length=20, verbose_name='年紀')),
                ('Variety', models.CharField(blank=True, max_length=20, verbose_name='品種')),
                ('Reason', models.CharField(blank=True, max_length=20, verbose_name='理由')),
                ('AcceptNum', models.CharField(blank=True, max_length=20, verbose_name='什麼')),
                ('ChipNum', models.CharField(blank=True, max_length=20, verbose_name='晶片號碼')),
                ('IsSterilization', models.CharField(blank=True, max_length=20, verbose_name='是否有結紮')),
                ('HairType', models.CharField(default='', max_length=20, verbose_name='毛色')),
                ('Note', models.TextField(blank=True, verbose_name='備註')),
                ('Resettlement', models.CharField(blank=True, max_length=30, verbose_name='收容所編號')),
                ('Phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('Email', models.EmailField(blank=True, max_length=254, verbose_name='信箱')),
                ('ChildreAnlong', models.CharField(blank=True, max_length=20, verbose_name='不知道1')),
                ('AnimalAnlong', models.CharField(blank=True, max_length=20, verbose_name='不知道2')),
                ('Bodyweight', models.CharField(blank=True, max_length=20, verbose_name='體重')),
                ('ImageName', models.ImageField(upload_to='pet/')),
            ],
        ),
    ]
